{% set name = "imbalanced-learn" %}
{% set version = "0.12.2" %}
{% set sha256 = "a80c56cedcb07124f266be62d3a5d2ab5b5779909a7343fdf1b993479662f6c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.17.3
    - scipy >=1.5.0
    - scikit-learn >=1.0.2
    - joblib >=1.1.0

test:
  requires:
    - pytest >=5.0.1
    - pytest-timeout
  imports:
    - imblearn
  commands:
    - pytest --timeout 300 --verbose --pyargs imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to balance data set using under- and over-sampling
  description: |
    imbalanced-learn is a python package offering a number of re-sampling
    techniques commonly used in datasets showing strong between-class imbalance.
    It is compatible with scikit-learn and is part of scikit-learn-contrib
    projects.
  doc_url: http://imbalanced-learn.org/en/stable/
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
