{% set name = "imbalanced-learn" %}
{% set version = "0.10.1" %}
{% set sha256 = "bc7609619ec3c38c442292928239ad3d10b5deb0af8a29c83822b7b57b319f8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - numpy
    - scipy >=1.3.2
    - scikit-learn >=1.0.2
    - joblib >=1.1.0

test:
  requires:
    - pytest >=5.0.1
    - pytest-timeout
  imports:
    - imblearn
  commands:
    - pip check
    - pytest --timeout 300 --verbose --pyargs imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to balance data set using under- and over-sampling
  description: |
    imbalanced-learn is a python package offering a number of re-sampling
    techniques commonly used in datasets showing strong between-class imbalance.
    It is compatible with scikit-learn and is part of scikit-learn-contrib
    projects.
  doc_url: https://imbalanced-learn.org/en/stable/
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
