{% set name = "imbalanced-learn" %}
{% set version = "0.13.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imbalanced_learn-{{ version }}.tar.gz
  sha256: d4a8d6372086982350d6de1c7e5b1ed5ece9e41bf93043b4d0e9ea1c422a6606

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.3,<3
    - scipy >=1.10.1,<2
    - scikit-learn >=1.3.2,<2
    - sklearn-compat >=0.1,<1
    - joblib >=1.1.1,<2
    - threadpoolctl >=2.0.0,<4

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=7.2.2
    - pytest-timeout
  imports:
    - imblearn
  commands:
    - pip check
    - pytest --timeout 300 --verbose --pyargs imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to balance data set using under- and over-sampling
  description: |
    imbalanced-learn is a python package offering a number of re-sampling
    techniques commonly used in datasets showing strong between-class imbalance.
    It is compatible with scikit-learn and is part of scikit-learn-contrib
    projects.
  doc_url: http://imbalanced-learn.org/en/stable/
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
